export const DELIVERY_COMPANY = "Digylog";

// Cities covered by Digylog (from digylog.com network).
export const DIGYLOG_CITIES = [
  "Agadir",
  "Al Hoceima",
  "Aourir",
  "Beni Mellal",
  "Berrechid",
  "Casablanca",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fes",
  "Guelmim",
  "Kenitra",
  "Khénifra",
  "Khouribga",
  "Laayoune",
  "Larache",
  "Marrakech",
  "Meknès",
  "Midelt",
  "Nador",
  "Ouarzazate",
  "Oujda",
  "Oulad Teima",
  "Rabat",
  "Safi",
  "Tanger",
  "Taroudant",
  "Taza",
  "Tétouan",
  "Tiznit",
] as const;
